<h1>Tables des matières<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Evaluation-de-Modele-selon-des-paramètres" data-toc-modified-id="Evaluation-de-Modele-selon-des-paramètres-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Evaluation de Modele selon des paramètres</a></span></li><li><span><a href="#Objectif" data-toc-modified-id="Objectif-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Objectif</a></span></li><li><span><a href="#Train-et-test-sur-tout-le-dataset" data-toc-modified-id="Train-et-test-sur-tout-le-dataset-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Train et test sur tout le dataset</a></span></li><li><span><a href="#Evaluation-procedure-#2:-Train/test-split" data-toc-modified-id="Evaluation-procedure-#2:-Train/test-split-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Evaluation procedure #2: Train/test split</a></span></li><li><span><a href="#Prediction-avec-un-echantillon-out-of-sample" data-toc-modified-id="Prediction-avec-un-echantillon-out-of-sample-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Prediction avec un echantillon out-of-sample</a></span></li></ul></div>

# Evaluation de Modele selon des paramètres

# Objectif
* Prédire l'espece d'une fleur iris en utilisant KNN avec K variable
* Trouver la valeur appropriée de K
* Obtenir le modèle qui généralise correctement 

# Train et test sur tout le dataset

* Apprentissage du modele sur tout le dataset.
* Effectur le Test du modele sur le meme dataset, 
* Evaluer et comparer la classe predite avec la vraie classe

In [28]:
# Lire iris data dans un DataFrame
import pandas as pd
from sklearn import datasets
print "chargement du dataset iris"
iris = datasets.load_iris()
#print iris.data


chargement du dataset iris


* utiliser KNN avec K = 50 par exemple

In [7]:
from sklearn.neighbors import KNeighborsClassifier
X = iris.data
y = iris.target
# instantier le modele
knn = KNeighborsClassifier(n_neighbors=50)
# Effectuer l'apprentissage du model sur tout le dataset
knn.fit(X, y)
# predire la réponse pour les observations dans X, test du model
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# stocker les réponses prédites dans y_pred
y_pred = knn.predict(X)
print y_pred

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 1 2 2 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2
 2 2]


* Determiner un metrique tel que Accuracy

In [10]:
# Metrique d'évaluation - Accuracy de classification

from sklearn import metrics
print metrics.accuracy_score(y, y_pred)

#conclusion ! Est ce qu'on a training accuracy ou testing accuracy ?

0.94


* utiliser KNN avec K = 1 maintenant

In [11]:
#calculer Accuracy
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X, y)
y_pred = knn.predict(X)
print metrics.accuracy_score(y, y_pred)

#conclusion: est ce qu'on a un problème avec cette approche ?


1.0


# Evaluation procedure #2: Train/test split

* Split du dataset en deux ensemble:  training set et testing set.
* apprentissage du modele sur le training set.
* Test du modele sur le testing set 
* Evaluer le modele

In [12]:
#utiliser la fonction train_test_split avec taille test de 40% sans random_state
# Utiliser X_train, X_test, y_train, y_test
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

#afficher les différentes shape
# before splitting
print X.shape

# after splitting
print X_train.shape
print X_test.shape
# before splitting
print y.shape

# after splitting
print y_train.shape
print y_test.shape
#afficher le premier element de chaque ensemble
print X_train[0]
print X_test[0]
print y_train[0]
print y_test[0]

(150, 4)
(90, 4)
(60, 4)
(150,)
(90,)
(60,)
[ 6.4  3.1  5.5  1.8]
[ 5.   3.5  1.6  0.6]
2
0


* Effet du paramètre random_state

* refaire le meme avec random_state = 4

In [13]:
# Utiliser X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)


#afficher les différentes shape
print X_train[0]
print X_test[0]
print y_train[0]
print y_test[0]

#afficher le premier element de chaque ensemble
#votre code ici

[ 4.6  3.4  1.4  0.3]
[ 6.4  2.8  5.6  2.1]
0
2


* Effectuer apprentissage avec K=1

In [19]:
#Etape 1: split en traning et test avec random state = 4
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

#Etape 2: faire l'apprentissage
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

#Etape 3: faire le test du modèle avec l'ensemble d'apprentissage
y_pred = knn.predict(X_test)

#Etape 4: determiner accuracy
print metrics.accuracy_score(y_test, y_pred)

#Est ce que vous avez une training accuracy ou testing accuracy ?

0.95


* Effectuer apprentissage avec K=50

In [20]:
#Etape 1: split en traning et test avec random state = 4
knn = KNeighborsClassifier(n_neighbors=50)

#Etape 2: faire l'apprentissage
knn.fit(X_train, y_train)

#Etape 3: faire le test du modèle avec l'ensemble d'apprentissage
y_pred = knn.predict(X_test)

#Etape 4: determiner accuracy
print metrics.accuracy_score(y_test, y_pred)

0.933333333333


In [21]:
#Comparer avec l'approche où un seul ensemble de données

#Votre conclusion

# Prediction avec un echantillon out-of-sample

* On prend un echantillon completement inconnu

In [42]:
import numpy as np
#Instantier le modele avec K égale à valeur optimale (comment?)
knn = KNeighborsClassifier(n_neighbors=6)

#Effectuer l'apprentissage avec X et y  (ne pas prendre X_train et y_train)
knn.fit(X, y)

#Faire une prediction avec l'échantillon [3,5,4,5]
tmp = np.array([3, 5, 4, 5]).reshape(1, -1)
y_pred = knn.predict(tmp)
print y_pred

[2]
